### ISSUE TITLE
support for tweed deluxe?

### ISSUE THREAD

**Issue by jgomer2001** [why-trv/yet-another-tonestack-calculator#1]
Hi @why-trv

It is amazingto see a new revamped calculator was born! how cool!

I wonder if you would like to go over my recent request on "TSC on the web" - jatalahd actually added the 5E3 tone stack and I'd love it to see it in YATSC too. See https://github.com/jatalahd/tsc/issues/10

If you could double check his analysis/implementation to ensure it is correct, it would be great. Unfortunately I don't have the knowledge required to contribute to the project.

Thanks in advance!

**Comment by why-trv** [comment]
Just ran a SPICE sim, and it does look about right. The question is, do people actually use the normal channel? Or maybe they always use the bright channel, or both jumpered? Do you have any info on that?

**Comment by jgomer2001** [comment]
no... a quick run on random forum posts reveals it is more a matter of taste and people are effectively using all three options: normal/bright/jumpered

btw this [video](https://youtu.be/VN2vqCxaeC0) is mentioned at several sites - it's long  though

**Comment by why-trv** [comment]
Added both normal and bright channel tonestacks. Seems to agree with what's being said in the video (though i haven't watched it all the way through).

Also, the 'global' mode comes in handy to kinda see the tonestack response depending on the channel used (only the tonestack of course):
https://tonestack.yuriturov.com/?s=eNpblljMkJj-NbFsRVKQ02_7NxpfD_XHaCUF-f62f5cGBklBIb_sGRgYkoLCftuf2xH4ulVuR0qQZ7AbVDQcTCcHhTnBGH5gRmJRoktiRWJZYknTosTMFNNU46TE5FVAnX5OyUYG2SCGH4gBNL85ydA30RFuDirXD4mbFOQD5KQ4A7WmGBoY5CU5G6aY6JkDaaMUUwODApCME1gGamUeHa0EACLabtI

**Comment by jgomer2001** [comment]
Nice, thank you!. I will watch the video as soon as I can. I'll add any comment if I have
