### ISSUE TITLE
Jerky sliders on mobile

### ISSUE THREAD

**Issue by ampetrosillo** [why-trv/yet-another-tonestack-calculator#4]
As mentioned at DIYStompboxes, here is a video of the issue.

It appears to start smoothly, but then movement is uneven. It also looks like the web page is larger than the width of the screen, as implied by the slight horizontal scrolling.

https://github.com/user-attachments/assets/3069ec9d-3b4a-4f46-9a97-ef5d6983b792

![Screenshot_20241009_225833_Chrome](https://github.com/user-attachments/assets/a226701d-48c6-4d90-b908-e6ea9fe71c3d)

**Comment by why-trv** [comment]
Thanks, I think I got it - please let me know if this helps

**Comment by ampetrosillo** [comment]
Perfect!
