### ISSUE TITLE
Add "Bandmaster" Tonestack

### ISSUE THREAD

**Issue by tristancollins** [why-trv/yet-another-tonestack-calculator#5]
Would you be able to add the "Bandmaster" stack from Merlin's preamp book? It's very similar to the Vox stack from TSC, but different enough.

Note the pins of the Bass pot are reversed. 

<img width="555" alt="image" src="https://github.com/user-attachments/assets/03aba3a3-352f-42a1-9de3-afb44a6c6263">

**Comment by tristancollins** [comment]
Here is an LTSpice simulation:
[Bandmaster.zip](https://github.com/user-attachments/files/17333701/Bandmaster.zip)

**Comment by why-trv** [comment]
I hope so :)
You can pretty much do it with the Vox stack by setting C2 to a large value, but still why not.
Which Bandmaster is it? The BF/SF ones probably have the standard AB763 stack, so I guess it's a blonde? Also if you have a link to the preamp schematic, please let me know

**Comment by why-trv** [comment]
Added in d9b997d4159c122b512ec2b1d637b0e362c75952.
I've decided to include the volume pot and bright cap as well
